# Generated by Django 5.1.4 on 2025-02-05 13:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormField',
            new_name='AccountFormField',
        ),
        migrations.RenameModel(
            old_name='FormFieldTranslation',
            new_name='AccountFormFieldTranslation',
        ),
        migrations.RenameModel(
            old_name='FormTemplate',
            new_name='AccountFormTemplate',
        ),
        migrations.RenameModel(
            old_name='FormTemplateTranslation',
            new_name='AccountFormTemplateTranslation',
        ),
        migrations.RenameModel(
            old_name='UserFormSubmission',
            new_name='AccountUserFormSubmission',
        ),
        migrations.AlterModelOptions(
            name='accountformfieldtranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'account form field Translation'},
        ),
        migrations.AlterModelOptions(
            name='accountformtemplatetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'account form template Translation'},
        ),
        migrations.AlterModelTable(
            name='accountformfieldtranslation',
            table='account_accountformfield_translation',
        ),
        migrations.AlterModelTable(
            name='accountformtemplatetranslation',
            table='account_accountformtemplate_translation',
        ),
    ]
