# Generated by Django 5.1.4 on 2025-02-05 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_formfield_accountformfield_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountUserFormSubmission',
            new_name='AccountFormSubmission',
        ),
        migrations.AddField(
            model_name='accountformtemplate',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountformtemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
