# Generated by Django 5.1.4 on 2025-02-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_accountuserformsubmission_accountformsubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountformfield',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
