# Generated by Django 5.1.4 on 2025-04-30 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_attribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='product',
        ),
    ]
