# Generated by Django 5.1.4 on 2025-01-10 18:35

import tokenshield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenshield', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', tokenshield.models.CustomUserManager()),
            ],
        ),
    ]
