# Generated by Django 5.1.4 on 2025-01-17 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokenshield', '0003_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
